# -*- coding: utf-8 -*-
"""
Y1 Helper Localization System
Supports: English UK, English US, English International, French, Spanish, Chinese, Russian, Japanese
"""

import locale
import os
from typing import Dict, Any

class LocalizationManager:
    def __init__(self):
        self.current_language = "en_US"
        self.translations = {}
        self._load_translations()
        self._detect_system_language()
    
    def _detect_system_language(self):
        """Detect system language and set appropriate locale"""
        try:
            # Get system locale
            system_locale = locale.getdefaultlocale()[0]
            if system_locale:
                # Map system locales to our supported languages
                locale_mapping = {
                    'en_GB': 'en_GB',
                    'en_US': 'en_US', 
                    'en': 'en_INT',
                    'fr_FR': 'fr_FR',
                    'fr': 'fr_FR',
                    'es_ES': 'es_ES',
                    'es': 'es_ES',
                    'zh_CN': 'zh_CN',
                    'zh': 'zh_CN',
                    'ru_RU': 'ru_RU',
                    'ru': 'ru_RU',
                    'ja_JP': 'ja_JP',
                    'ja': 'ja_JP'
                }
                
                detected_lang = locale_mapping.get(system_locale, 'en_US')
                self.set_language(detected_lang)
        except Exception:
            # Fallback to English US
            self.set_language('en_US')
    
    def _load_translations(self):
        """Load all translation strings"""
        self.translations = {
            'en_US': {
                # Main UI
                'title': 'Y1 Helper v{version} - created by Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Installer Features Temporarily Unavailable',
                
                # Menu items
                'menu_file': 'File',
                'menu_edit': 'Edit',
                'menu_view': 'View',
                'menu_help': 'Help',
                'menu_apps': 'Apps',
                'menu_language': 'Language',
                
                # Apps menu
                'browse_apks': 'Browse APKs...',
                'install_apps': 'Install Apps',
                'user_apps': 'User Apps ({count})',
                'system_apps': 'System Apps ({count})',
                'error_loading_user_apps': 'Error loading user apps',
                'no_user_apps': 'No user apps installed',
                'error_loading_system_apps': 'Error loading system apps',
                'no_system_apps': 'No system apps found',
                'launch_app': 'Launch',
                'uninstall_app': 'Uninstall',
                'app_info': 'App Info',
                
                # Language menu
                'language_english_us': 'English (US)',
                'language_english_uk': 'English (UK)',
                'language_english_international': 'English (International)',
                'language_french': 'Français',
                'language_spanish': 'Español',
                'language_chinese': '中文',
                'language_russian': 'Русский',
                'language_japanese': '日本語',
                
                # Device status
                'device_connected': 'Device Connected',
                'device_disconnected': 'Device Disconnected',
                'connecting_device': 'Connecting to device...',
                'device_not_found': 'Device not found',
                
                # Buttons and controls
                'connect': 'Connect',
                'disconnect': 'Disconnect',
                'refresh': 'Refresh',
                'install': 'Install',
                'uninstall': 'Uninstall',
                'cancel': 'Cancel',
                'ok': 'OK',
                'yes': 'Yes',
                'no': 'No',
                'close': 'Close',
                'save': 'Save',
                'apply': 'Apply',
                
                # Messages
                'operation_successful': 'Operation completed successfully',
                'operation_failed': 'Operation failed',
                'please_wait': 'Please wait...',
                'loading': 'Loading...',
                'error_occurred': 'An error occurred',
                'not_implemented': 'This feature is not yet implemented',
                
                # App detection
                'detecting_app': 'Detecting current app...',
                'app_detected': 'App detected: {app}',
                'no_app_detected': 'No app detected',
                
                # Cache and updates
                'cache_refreshing': 'Refreshing cache...',
                'cache_refreshed': 'Cache refreshed successfully',
                'checking_updates': 'Checking for updates...',
                'update_available': 'Update available',
                'no_updates': 'No updates available',
                
                # Firmware
                'firmware_installation': 'Firmware Installation',
                'select_firmware': 'Select Firmware',
                'flashing_firmware': 'Flashing firmware...',
                'firmware_flash_complete': 'Firmware flash completed',
                'firmware_flash_failed': 'Firmware flash failed',
                
                # Process termination
                'terminating_processes': 'Terminating ADB and Python processes...',
                'processes_terminated': 'Processes terminated successfully',
                'save_work_warning': 'Please save your work before continuing',
                
                # Error messages
                'connection_error': 'Connection error',
                'timeout_error': 'Operation timed out',
                'permission_error': 'Permission denied',
                'file_not_found': 'File not found',
                'invalid_input': 'Invalid input',
                
                # Status messages
                'ready': 'Ready',
                'busy': 'Busy',
                'idle': 'Idle',
                'processing': 'Processing...',
                'completed': 'Completed',
                'failed': 'Failed',
                'cancelled': 'Cancelled'
            },
            
            'en_GB': {
                # British English variations
                'title': 'Y1 Helper v{version} - created by Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Installer Features Temporarily Unavailable',
                'menu_file': 'File',
                'menu_edit': 'Edit', 
                'menu_view': 'View',
                'menu_help': 'Help',
                'menu_apps': 'Apps',
                'menu_language': 'Language',
                'browse_apks': 'Browse APKs...',
                'install_apps': 'Install Apps',
                'user_apps': 'User Apps ({count})',
                'system_apps': 'System Apps ({count})',
                'error_loading_user_apps': 'Error loading user apps',
                'no_user_apps': 'No user apps installed',
                'error_loading_system_apps': 'Error loading system apps',
                'no_system_apps': 'No system apps found',
                'launch_app': 'Launch',
                'uninstall_app': 'Uninstall',
                'app_info': 'App Info',
                'language_english_us': 'English (US)',
                'language_english_uk': 'English (UK)',
                'language_english_international': 'English (International)',
                'language_french': 'Français',
                'language_spanish': 'Español',
                'language_chinese': '中文',
                'language_russian': 'Русский',
                'language_japanese': '日本語',
                'device_connected': 'Device Connected',
                'device_disconnected': 'Device Disconnected',
                'connecting_device': 'Connecting to device...',
                'device_not_found': 'Device not found',
                'connect': 'Connect',
                'disconnect': 'Disconnect',
                'refresh': 'Refresh',
                'install': 'Install',
                'uninstall': 'Uninstall',
                'cancel': 'Cancel',
                'ok': 'OK',
                'yes': 'Yes',
                'no': 'No',
                'close': 'Close',
                'save': 'Save',
                'apply': 'Apply',
                'operation_successful': 'Operation completed successfully',
                'operation_failed': 'Operation failed',
                'please_wait': 'Please wait...',
                'loading': 'Loading...',
                'error_occurred': 'An error occurred',
                'not_implemented': 'This feature is not yet implemented',
                'detecting_app': 'Detecting current app...',
                'app_detected': 'App detected: {app}',
                'no_app_detected': 'No app detected',
                'cache_refreshing': 'Refreshing cache...',
                'cache_refreshed': 'Cache refreshed successfully',
                'checking_updates': 'Checking for updates...',
                'update_available': 'Update available',
                'no_updates': 'No updates available',
                'firmware_installation': 'Firmware Installation',
                'select_firmware': 'Select Firmware',
                'flashing_firmware': 'Flashing firmware...',
                'firmware_flash_complete': 'Firmware flash completed',
                'firmware_flash_failed': 'Firmware flash failed',
                'terminating_processes': 'Terminating ADB and Python processes...',
                'processes_terminated': 'Processes terminated successfully',
                'save_work_warning': 'Please save your work before continuing',
                'connection_error': 'Connection error',
                'timeout_error': 'Operation timed out',
                'permission_error': 'Permission denied',
                'file_not_found': 'File not found',
                'invalid_input': 'Invalid input',
                'ready': 'Ready',
                'busy': 'Busy',
                'idle': 'Idle',
                'processing': 'Processing...',
                'completed': 'Completed',
                'failed': 'Failed',
                'cancelled': 'Cancelled'
            },
            
            'en_INT': {
                # International English (same as US for now)
                'title': 'Y1 Helper v{version} - created by Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Installer Features Temporarily Unavailable',
                'menu_file': 'File',
                'menu_edit': 'Edit',
                'menu_view': 'View', 
                'menu_help': 'Help',
                'menu_apps': 'Apps',
                'menu_language': 'Language',
                'browse_apks': 'Browse APKs...',
                'install_apps': 'Install Apps',
                'user_apps': 'User Apps ({count})',
                'system_apps': 'System Apps ({count})',
                'error_loading_user_apps': 'Error loading user apps',
                'no_user_apps': 'No user apps installed',
                'error_loading_system_apps': 'Error loading system apps',
                'no_system_apps': 'No system apps found',
                'launch_app': 'Launch',
                'uninstall_app': 'Uninstall',
                'app_info': 'App Info',
                'language_english_us': 'English (US)',
                'language_english_uk': 'English (UK)',
                'language_english_international': 'English (International)',
                'language_french': 'Français',
                'language_spanish': 'Español',
                'language_chinese': '中文',
                'language_russian': 'Русский',
                'language_japanese': '日本語',
                'device_connected': 'Device Connected',
                'device_disconnected': 'Device Disconnected',
                'connecting_device': 'Connecting to device...',
                'device_not_found': 'Device not found',
                'connect': 'Connect',
                'disconnect': 'Disconnect',
                'refresh': 'Refresh',
                'install': 'Install',
                'uninstall': 'Uninstall',
                'cancel': 'Cancel',
                'ok': 'OK',
                'yes': 'Yes',
                'no': 'No',
                'close': 'Close',
                'save': 'Save',
                'apply': 'Apply',
                'operation_successful': 'Operation completed successfully',
                'operation_failed': 'Operation failed',
                'please_wait': 'Please wait...',
                'loading': 'Loading...',
                'error_occurred': 'An error occurred',
                'not_implemented': 'This feature is not yet implemented',
                'detecting_app': 'Detecting current app...',
                'app_detected': 'App detected: {app}',
                'no_app_detected': 'No app detected',
                'cache_refreshing': 'Refreshing cache...',
                'cache_refreshed': 'Cache refreshed successfully',
                'checking_updates': 'Checking for updates...',
                'update_available': 'Update available',
                'no_updates': 'No updates available',
                'firmware_installation': 'Firmware Installation',
                'select_firmware': 'Select Firmware',
                'flashing_firmware': 'Flashing firmware...',
                'firmware_flash_complete': 'Firmware flash completed',
                'firmware_flash_failed': 'Firmware flash failed',
                'terminating_processes': 'Terminating ADB and Python processes...',
                'processes_terminated': 'Processes terminated successfully',
                'save_work_warning': 'Please save your work before continuing',
                'connection_error': 'Connection error',
                'timeout_error': 'Operation timed out',
                'permission_error': 'Permission denied',
                'file_not_found': 'File not found',
                'invalid_input': 'Invalid input',
                'ready': 'Ready',
                'busy': 'Busy',
                'idle': 'Idle',
                'processing': 'Processing...',
                'completed': 'Completed',
                'failed': 'Failed',
                'cancelled': 'Cancelled'
            },
            
            'fr_FR': {
                # French translations
                'title': 'Y1 Helper v{version} - créé par Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Fonctionnalités d\'installation temporairement indisponibles',
                'menu_file': 'Fichier',
                'menu_edit': 'Modifier',
                'menu_view': 'Affichage',
                'menu_help': 'Aide',
                'menu_apps': 'Applications',
                'menu_language': 'Langue',
                'browse_apks': 'Parcourir les APK...',
                'install_apps': 'Installer des applications',
                'user_apps': 'Applications utilisateur ({count})',
                'system_apps': 'Applications système ({count})',
                'error_loading_user_apps': 'Erreur lors du chargement des applications utilisateur',
                'no_user_apps': 'Aucune application utilisateur installée',
                'error_loading_system_apps': 'Erreur lors du chargement des applications système',
                'no_system_apps': 'Aucune application système trouvée',
                'launch_app': 'Lancer',
                'uninstall_app': 'Désinstaller',
                'app_info': 'Informations sur l\'application',
                'language_english_us': 'Anglais (États-Unis)',
                'language_english_uk': 'Anglais (Royaume-Uni)',
                'language_english_international': 'Anglais (International)',
                'language_french': 'Français',
                'language_spanish': 'Espagnol',
                'language_chinese': 'Chinois',
                'language_russian': 'Russe',
                'language_japanese': 'Japonais',
                'device_connected': 'Appareil connecté',
                'device_disconnected': 'Appareil déconnecté',
                'connecting_device': 'Connexion à l\'appareil...',
                'device_not_found': 'Appareil non trouvé',
                'connect': 'Connecter',
                'disconnect': 'Déconnecter',
                'refresh': 'Actualiser',
                'install': 'Installer',
                'uninstall': 'Désinstaller',
                'cancel': 'Annuler',
                'ok': 'OK',
                'yes': 'Oui',
                'no': 'Non',
                'close': 'Fermer',
                'save': 'Enregistrer',
                'apply': 'Appliquer',
                'operation_successful': 'Opération terminée avec succès',
                'operation_failed': 'Opération échouée',
                'please_wait': 'Veuillez patienter...',
                'loading': 'Chargement...',
                'error_occurred': 'Une erreur s\'est produite',
                'not_implemented': 'Cette fonctionnalité n\'est pas encore implémentée',
                'detecting_app': 'Détection de l\'application actuelle...',
                'app_detected': 'Application détectée : {app}',
                'no_app_detected': 'Aucune application détectée',
                'cache_refreshing': 'Actualisation du cache...',
                'cache_refreshed': 'Cache actualisé avec succès',
                'checking_updates': 'Vérification des mises à jour...',
                'update_available': 'Mise à jour disponible',
                'no_updates': 'Aucune mise à jour disponible',
                'firmware_installation': 'Installation du firmware',
                'select_firmware': 'Sélectionner le firmware',
                'flashing_firmware': 'Installation du firmware...',
                'firmware_flash_complete': 'Installation du firmware terminée',
                'firmware_flash_failed': 'Échec de l\'installation du firmware',
                'terminating_processes': 'Terminaison des processus ADB et Python...',
                'processes_terminated': 'Processus terminés avec succès',
                'save_work_warning': 'Veuillez sauvegarder votre travail avant de continuer',
                'connection_error': 'Erreur de connexion',
                'timeout_error': 'Délai d\'attente dépassé',
                'permission_error': 'Permission refusée',
                'file_not_found': 'Fichier non trouvé',
                'invalid_input': 'Entrée invalide',
                'ready': 'Prêt',
                'busy': 'Occupé',
                'idle': 'Inactif',
                'processing': 'Traitement...',
                'completed': 'Terminé',
                'failed': 'Échoué',
                'cancelled': 'Annulé'
            },
            
            'es_ES': {
                # Spanish translations
                'title': 'Y1 Helper v{version} - creado por Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Características del instalador temporalmente no disponibles',
                'menu_file': 'Archivo',
                'menu_edit': 'Editar',
                'menu_view': 'Ver',
                'menu_help': 'Ayuda',
                'menu_apps': 'Aplicaciones',
                'menu_language': 'Idioma',
                'browse_apks': 'Examinar APKs...',
                'install_apps': 'Instalar aplicaciones',
                'user_apps': 'Aplicaciones de usuario ({count})',
                'system_apps': 'Aplicaciones del sistema ({count})',
                'error_loading_user_apps': 'Error al cargar aplicaciones de usuario',
                'no_user_apps': 'No hay aplicaciones de usuario instaladas',
                'error_loading_system_apps': 'Error al cargar aplicaciones del sistema',
                'no_system_apps': 'No se encontraron aplicaciones del sistema',
                'launch_app': 'Ejecutar',
                'uninstall_app': 'Desinstalar',
                'app_info': 'Información de la aplicación',
                'language_english_us': 'Inglés (EE.UU.)',
                'language_english_uk': 'Inglés (Reino Unido)',
                'language_english_international': 'Inglés (Internacional)',
                'language_french': 'Francés',
                'language_spanish': 'Español',
                'language_chinese': 'Chino',
                'language_russian': 'Ruso',
                'language_japanese': 'Japonés',
                'device_connected': 'Dispositivo conectado',
                'device_disconnected': 'Dispositivo desconectado',
                'connecting_device': 'Conectando al dispositivo...',
                'device_not_found': 'Dispositivo no encontrado',
                'connect': 'Conectar',
                'disconnect': 'Desconectar',
                'refresh': 'Actualizar',
                'install': 'Instalar',
                'uninstall': 'Desinstalar',
                'cancel': 'Cancelar',
                'ok': 'OK',
                'yes': 'Sí',
                'no': 'No',
                'close': 'Cerrar',
                'save': 'Guardar',
                'apply': 'Aplicar',
                'operation_successful': 'Operación completada exitosamente',
                'operation_failed': 'Operación fallida',
                'please_wait': 'Por favor espere...',
                'loading': 'Cargando...',
                'error_occurred': 'Ocurrió un error',
                'not_implemented': 'Esta característica aún no está implementada',
                'detecting_app': 'Detectando aplicación actual...',
                'app_detected': 'Aplicación detectada: {app}',
                'no_app_detected': 'No se detectó aplicación',
                'cache_refreshing': 'Actualizando caché...',
                'cache_refreshed': 'Caché actualizado exitosamente',
                'checking_updates': 'Verificando actualizaciones...',
                'update_available': 'Actualización disponible',
                'no_updates': 'No hay actualizaciones disponibles',
                'firmware_installation': 'Instalación de firmware',
                'select_firmware': 'Seleccionar firmware',
                'flashing_firmware': 'Instalando firmware...',
                'firmware_flash_complete': 'Instalación de firmware completada',
                'firmware_flash_failed': 'Instalación de firmware fallida',
                'terminating_processes': 'Terminando procesos ADB y Python...',
                'processes_terminated': 'Procesos terminados exitosamente',
                'save_work_warning': 'Por favor guarde su trabajo antes de continuar',
                'connection_error': 'Error de conexión',
                'timeout_error': 'Tiempo de espera agotado',
                'permission_error': 'Permiso denegado',
                'file_not_found': 'Archivo no encontrado',
                'invalid_input': 'Entrada inválida',
                'ready': 'Listo',
                'busy': 'Ocupado',
                'idle': 'Inactivo',
                'processing': 'Procesando...',
                'completed': 'Completado',
                'failed': 'Fallido',
                'cancelled': 'Cancelado'
            },
            
            'zh_CN': {
                # Chinese translations
                'title': 'Y1 Helper v{version} - 由 Ryan Specter 创建 - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - 安装程序功能暂时不可用',
                'menu_file': '文件',
                'menu_edit': '编辑',
                'menu_view': '视图',
                'menu_help': '帮助',
                'menu_apps': '应用程序',
                'menu_language': '语言',
                'browse_apks': '浏览 APK...',
                'install_apps': '安装应用程序',
                'user_apps': '用户应用程序 ({count})',
                'system_apps': '系统应用程序 ({count})',
                'error_loading_user_apps': '加载用户应用程序时出错',
                'no_user_apps': '未安装用户应用程序',
                'error_loading_system_apps': '加载系统应用程序时出错',
                'no_system_apps': '未找到系统应用程序',
                'launch_app': '启动',
                'uninstall_app': '卸载',
                'app_info': '应用程序信息',
                'language_english_us': '英语（美国）',
                'language_english_uk': '英语（英国）',
                'language_english_international': '英语（国际）',
                'language_french': '法语',
                'language_spanish': '西班牙语',
                'language_chinese': '中文',
                'language_russian': '俄语',
                'language_japanese': '日语',
                'device_connected': '设备已连接',
                'device_disconnected': '设备已断开',
                'connecting_device': '正在连接设备...',
                'device_not_found': '未找到设备',
                'connect': '连接',
                'disconnect': '断开',
                'refresh': '刷新',
                'install': '安装',
                'uninstall': '卸载',
                'cancel': '取消',
                'ok': '确定',
                'yes': '是',
                'no': '否',
                'close': '关闭',
                'save': '保存',
                'apply': '应用',
                'operation_successful': '操作成功完成',
                'operation_failed': '操作失败',
                'please_wait': '请稍候...',
                'loading': '加载中...',
                'error_occurred': '发生错误',
                'not_implemented': '此功能尚未实现',
                'detecting_app': '正在检测当前应用程序...',
                'app_detected': '检测到应用程序：{app}',
                'no_app_detected': '未检测到应用程序',
                'cache_refreshing': '正在刷新缓存...',
                'cache_refreshed': '缓存刷新成功',
                'checking_updates': '正在检查更新...',
                'update_available': '有可用更新',
                'no_updates': '没有可用更新',
                'firmware_installation': '固件安装',
                'select_firmware': '选择固件',
                'flashing_firmware': '正在安装固件...',
                'firmware_flash_complete': '固件安装完成',
                'firmware_flash_failed': '固件安装失败',
                'terminating_processes': '正在终止 ADB 和 Python 进程...',
                'processes_terminated': '进程终止成功',
                'save_work_warning': '请保存您的工作后再继续',
                'connection_error': '连接错误',
                'timeout_error': '操作超时',
                'permission_error': '权限被拒绝',
                'file_not_found': '文件未找到',
                'invalid_input': '输入无效',
                'ready': '就绪',
                'busy': '忙碌',
                'idle': '空闲',
                'processing': '处理中...',
                'completed': '已完成',
                'failed': '失败',
                'cancelled': '已取消'
            },
            
            'ru_RU': {
                # Russian translations
                'title': 'Y1 Helper v{version} - создано Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Функции установщика временно недоступны',
                'menu_file': 'Файл',
                'menu_edit': 'Правка',
                'menu_view': 'Вид',
                'menu_help': 'Справка',
                'menu_apps': 'Приложения',
                'menu_language': 'Язык',
                'browse_apks': 'Обзор APK...',
                'install_apps': 'Установить приложения',
                'user_apps': 'Пользовательские приложения ({count})',
                'system_apps': 'Системные приложения ({count})',
                'error_loading_user_apps': 'Ошибка загрузки пользовательских приложений',
                'no_user_apps': 'Пользовательские приложения не установлены',
                'error_loading_system_apps': 'Ошибка загрузки системных приложений',
                'no_system_apps': 'Системные приложения не найдены',
                'launch_app': 'Запустить',
                'uninstall_app': 'Удалить',
                'app_info': 'Информация о приложении',
                'language_english_us': 'Английский (США)',
                'language_english_uk': 'Английский (Великобритания)',
                'language_english_international': 'Английский (Международный)',
                'language_french': 'Французский',
                'language_spanish': 'Испанский',
                'language_chinese': 'Китайский',
                'language_russian': 'Русский',
                'language_japanese': 'Японский',
                'device_connected': 'Устройство подключено',
                'device_disconnected': 'Устройство отключено',
                'connecting_device': 'Подключение к устройству...',
                'device_not_found': 'Устройство не найдено',
                'connect': 'Подключить',
                'disconnect': 'Отключить',
                'refresh': 'Обновить',
                'install': 'Установить',
                'uninstall': 'Удалить',
                'cancel': 'Отмена',
                'ok': 'OK',
                'yes': 'Да',
                'no': 'Нет',
                'close': 'Закрыть',
                'save': 'Сохранить',
                'apply': 'Применить',
                'operation_successful': 'Операция успешно завершена',
                'operation_failed': 'Операция не удалась',
                'please_wait': 'Пожалуйста, подождите...',
                'loading': 'Загрузка...',
                'error_occurred': 'Произошла ошибка',
                'not_implemented': 'Эта функция еще не реализована',
                'detecting_app': 'Обнаружение текущего приложения...',
                'app_detected': 'Приложение обнаружено: {app}',
                'no_app_detected': 'Приложение не обнаружено',
                'cache_refreshing': 'Обновление кэша...',
                'cache_refreshed': 'Кэш успешно обновлен',
                'checking_updates': 'Проверка обновлений...',
                'update_available': 'Доступно обновление',
                'no_updates': 'Обновления недоступны',
                'firmware_installation': 'Установка прошивки',
                'select_firmware': 'Выбрать прошивку',
                'flashing_firmware': 'Установка прошивки...',
                'firmware_flash_complete': 'Установка прошивки завершена',
                'firmware_flash_failed': 'Установка прошивки не удалась',
                'terminating_processes': 'Завершение процессов ADB и Python...',
                'processes_terminated': 'Процессы успешно завершены',
                'save_work_warning': 'Пожалуйста, сохраните вашу работу перед продолжением',
                'connection_error': 'Ошибка подключения',
                'timeout_error': 'Превышено время ожидания',
                'permission_error': 'Доступ запрещен',
                'file_not_found': 'Файл не найден',
                'invalid_input': 'Неверный ввод',
                'ready': 'Готов',
                'busy': 'Занят',
                'idle': 'Простой',
                'processing': 'Обработка...',
                'completed': 'Завершено',
                'failed': 'Не удалось',
                'cancelled': 'Отменено'
            },
            
            'ja_JP': {
                # Japanese translations
                'title': 'Y1 Helper v{version} - Ryan Specter 作成 - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - インストーラー機能が一時的に利用できません',
                'menu_file': 'ファイル',
                'menu_edit': '編集',
                'menu_view': '表示',
                'menu_help': 'ヘルプ',
                'menu_apps': 'アプリ',
                'menu_language': '言語',
                'browse_apks': 'APKを参照...',
                'install_apps': 'アプリをインストール',
                'user_apps': 'ユーザーアプリ ({count})',
                'system_apps': 'システムアプリ ({count})',
                'error_loading_user_apps': 'ユーザーアプリの読み込みエラー',
                'no_user_apps': 'ユーザーアプリがインストールされていません',
                'error_loading_system_apps': 'システムアプリの読み込みエラー',
                'no_system_apps': 'システムアプリが見つかりません',
                'launch_app': '起動',
                'uninstall_app': 'アンインストール',
                'app_info': 'アプリ情報',
                'language_english_us': '英語（アメリカ）',
                'language_english_uk': '英語（イギリス）',
                'language_english_international': '英語（国際）',
                'language_french': 'フランス語',
                'language_spanish': 'スペイン語',
                'language_chinese': '中国語',
                'language_russian': 'ロシア語',
                'language_japanese': '日本語',
                'device_connected': 'デバイスが接続されました',
                'device_disconnected': 'デバイスが切断されました',
                'connecting_device': 'デバイスに接続中...',
                'device_not_found': 'デバイスが見つかりません',
                'connect': '接続',
                'disconnect': '切断',
                'refresh': '更新',
                'install': 'インストール',
                'uninstall': 'アンインストール',
                'cancel': 'キャンセル',
                'ok': 'OK',
                'yes': 'はい',
                'no': 'いいえ',
                'close': '閉じる',
                'save': '保存',
                'apply': '適用',
                'operation_successful': '操作が正常に完了しました',
                'operation_failed': '操作が失敗しました',
                'please_wait': 'お待ちください...',
                'loading': '読み込み中...',
                'error_occurred': 'エラーが発生しました',
                'not_implemented': 'この機能はまだ実装されていません',
                'detecting_app': '現在のアプリを検出中...',
                'app_detected': 'アプリが検出されました: {app}',
                'no_app_detected': 'アプリが検出されませんでした',
                'cache_refreshing': 'キャッシュを更新中...',
                'cache_refreshed': 'キャッシュが正常に更新されました',
                'checking_updates': '更新を確認中...',
                'update_available': '更新が利用可能です',
                'no_updates': '更新は利用できません',
                'firmware_installation': 'ファームウェアのインストール',
                'select_firmware': 'ファームウェアを選択',
                'flashing_firmware': 'ファームウェアをインストール中...',
                'firmware_flash_complete': 'ファームウェアのインストールが完了しました',
                'firmware_flash_failed': 'ファームウェアのインストールが失敗しました',
                'terminating_processes': 'ADBとPythonプロセスを終了中...',
                'processes_terminated': 'プロセスが正常に終了しました',
                'save_work_warning': '続行する前に作業を保存してください',
                'connection_error': '接続エラー',
                'timeout_error': 'タイムアウトエラー',
                'permission_error': '権限が拒否されました',
                'file_not_found': 'ファイルが見つかりません',
                'invalid_input': '無効な入力',
                'ready': '準備完了',
                'busy': 'ビジー',
                'idle': 'アイドル',
                'processing': '処理中...',
                'completed': '完了',
                'failed': '失敗',
                'cancelled': 'キャンセル'
            }
        }
    
    def set_language(self, language_code: str):
        """Set the current language"""
        if language_code in self.translations:
            self.current_language = language_code
            return True
        return False
    
    def get_text(self, key: str, **kwargs) -> str:
        """Get translated text for the given key"""
        try:
            if self.current_language in self.translations:
                if key in self.translations[self.current_language]:
                    text = self.translations[self.current_language][key]
                    # Format the text with any provided parameters
                    if kwargs:
                        text = text.format(**kwargs)
                    return text
            
            # Fallback to English US if translation not found
            if key in self.translations['en_US']:
                text = self.translations['en_US'][key]
                if kwargs:
                    text = text.format(**kwargs)
                return text
            
            # Return the key itself if no translation found
            return key
            
        except Exception:
            return key
    
    def get_supported_languages(self) -> Dict[str, str]:
        """Get list of supported languages with their display names"""
        return {
            'en_US': self.get_text('language_english_us'),
            'en_GB': self.get_text('language_english_uk'),
            'en_INT': self.get_text('language_english_international'),
            'fr_FR': self.get_text('language_french'),
            'es_ES': self.get_text('language_spanish'),
            'zh_CN': self.get_text('language_chinese'),
            'ru_RU': self.get_text('language_russian'),
            'ja_JP': self.get_text('language_japanese')
        }
    
    def get_current_language(self) -> str:
        """Get current language code"""
        return self.current_language

# Global instance
localization_manager = LocalizationManager()

def get_text(key: str, **kwargs) -> str:
    """Global function to get translated text"""
    return localization_manager.get_text(key, **kwargs)

def set_language(language_code: str) -> bool:
    """Global function to set language"""
    return localization_manager.set_language(language_code)

def get_supported_languages() -> Dict[str, str]:
    """Global function to get supported languages"""
    return localization_manager.get_supported_languages()
