# -*- coding: utf-8 -*-
"""
Y1 Helper Localization System
Supports: English US only
"""

import os
from typing import Dict, Any

class LocalizationManager:
    def __init__(self):
        self.current_language = "en_US"
        self.translations = {}
        self._load_translations()
    

    
    def _load_translations(self):
        """Load all translation strings"""
        self.translations = {
            'en_US': {
                # Main UI
                'title': 'Y1 Helper v{version} - created by Ryan Specter - u/respectyarn',
                'title_rate_limited': 'Y1 Helper v{version} - Installer Features Temporarily Unavailable',
                
                # Ready placeholder
                'ready_for_y1_connection': 'Ready for Y1 Connection',
                'first_time_instructions': 'If this is your first time using Y1 Helper, you can enable its features by turning off your Y1, unplugging it, and selecting Update or Restore.',
                'rockbox_rom_info': "You'll then be able to control your device from the PC and install custom firmwares, like the current Rockbox ROM from Multiwirth",
                
                # Device repair dialog
                'how_to_repair_device': 'How to Repair a Device',
                'repair_instructions': 'If something has gone wrong, don\'t panic! Please unplug your Y1 and turn it off by placing a sim ejector or paperclip in the hole between the headphone jack and charging port. This will turn it off and allow it to install firmware again. Please choose a firmware from the menu again and when asked to connect your device, plug in your powered-off Y1 and wait. The terminal window will show the progress of the update.',
                'repair_fallback': 'Try to install your firmware in Y1 Helper again and if this doesn\'t work, please use the Manual Install Guide.',
                'manual_install_guide': 'Manual Install Guide',
                
                # Firmware installation dialog
                'how_to_update_firmware': 'How to Update / Install / Get Custom Firmware',
                'firmware_instructions': 'Simply turn off your Y1 and click Update or Restore to begin. You will not lose any music stored on your Y1 in this process. When asked to do so, connect your powered-off Y1 and wait patiently. The Terminal window will display the progress of flashing.',
                'firmware_troubleshooting': 'If something goes wrong, don\'t panic. Y1 Helper should be able to fix it with another firmware install. Refer to the "How to repair a device" section.',
                'how_to_repair_device_link': 'How to repair a device',
                
                # Menu items
                'menu_file': 'File',
                'menu_edit': 'Edit',
                'menu_view': 'View',
                'menu_help': 'Help',
                'menu_device': 'Device',
                'menu_apps': 'Apps',
                'menu_language': 'Language',
                'menu_debug': 'Debug',
                
                # Apps menu
                'browse_apks': 'Browse APKs...',
                'install_apps': 'Install Apps',
                'user_apps': 'User Apps ({count})',
                'system_apps': 'System Apps ({count})',
                'error_loading_user_apps': 'Error loading user apps',
                'no_user_apps': 'No user apps installed',
                'error_loading_system_apps': 'Error loading system apps',
                'no_system_apps': 'No system apps found',
                'launch_app': 'Launch',
                'uninstall_app': 'Uninstall',
                'app_info': 'App Info',
                
                # Language menu
                'language_english_us': 'English (US)',
                'language_english_uk': 'English (UK)',
                'language_english_international': 'English (International)',
                'language_french': 'Français',
                'language_spanish': 'Español',
                'language_chinese': '中文',
                'language_russian': 'Русский',
                'language_japanese': '日本語',
                
                # Device status
                'device_connected': 'Device Connected',
                'device_disconnected': 'Device Disconnected',
                'connecting_device': 'Connecting to device...',
                'device_not_found': 'Device not found',
                
                # Wireless ADB
                'wireless_adb': 'Wireless ADB',
                'enable_wireless_adb': 'Enable Wireless ADB',
                'wireless_adb_enabled': 'Wireless ADB Enabled',
                'wireless_adb_disabled': 'Wireless ADB Disabled',
                'enter_device_ip': 'Enter Device IP Address',
                'device_ip_prompt': 'Please enter the IP address of your device:',
                'connecting_wireless': 'Connecting to device wirelessly...',
                'wireless_connection_success': 'Wireless connection established successfully!',
                'wireless_connection_failed': 'Failed to connect wirelessly. Please check the IP address and try again.',
                'wireless_adb_port': 'Wireless ADB Port',
                'wireless_adb_port_prompt': 'Enter the wireless ADB port (default: 5555):',
                'wireless_adb_instructions': 'To enable wireless ADB:\n1. Connect your device via USB first\n2. Click "Enable Wireless ADB"\n3. Enter your device IP address\n4. Disconnect USB and use wirelessly',
                
                # Buttons and controls
                'connect': 'Connect',
                'disconnect': 'Disconnect',
                'refresh': 'Refresh',
                'install': 'Install',
                'uninstall': 'Uninstall',
                'cancel': 'Cancel',
                'ok': 'OK',
                'yes': 'Yes',
                'no': 'No',
                'close': 'Close',
                'save': 'Save',
                'apply': 'Apply',
                
                # Messages
                'operation_successful': 'Operation completed successfully',
                'operation_failed': 'Operation failed',
                'please_wait': 'Please wait...',
                'loading': 'Loading...',
                'error_occurred': 'An error occurred',
                'not_implemented': 'This feature is not yet implemented',
                
                # App detection
                'detecting_app': 'Detecting current app...',
                'app_detected': 'App detected: {app}',
                'no_app_detected': 'No app detected',
                
                # Cache and updates
                'cache_refreshing': 'Refreshing cache...',
                'cache_refreshed': 'Cache refreshed successfully',
                'checking_updates': 'Checking for updates...',
                'update_available': 'Update available',
                'no_updates': 'No updates available',
                
                # Firmware
                'firmware_installation': 'Firmware Installation',
                'select_firmware': 'Select Firmware',
                'flashing_firmware': 'Flashing firmware...',
                'firmware_flash_complete': 'Firmware flash completed',
                'firmware_flash_failed': 'Firmware flash failed',
                
                # Firmware Progress Indicators
                'please_unplug_turn_off': 'Please Unplug and Turn off Your Y1 Now',
                'device_detected_flashing': 'Device Detected, now flashing...',
                'please_wait': 'Please wait...',
                'searching_usb_device': 'Flash tool is searching for USB device. Please connect your turned-off Y1 device.',
                'downloading_firmware': 'Downloading firmware... {percent}%',
                'flashing_firmware_progress': 'Flashing firmware... {percent}%',
                'preparing': 'Preparing: {message}',
                'flashing': 'Flashing: {message}',
                'finalizing': 'Finalizing: {message}',
                'flash_completed_success': 'Flash completed successfully!',
                'flash_completed_verification': 'Flash completed - verification needed',
                'flash_error_occurred': 'Flash error occurred',
                'connection_failed': 'Connection failed',
                'flash_tool_output': 'Flash Tool Output',
                
                # New firmware validation and error messages
                'rom_zip_not_found': 'rom.zip not found in firmware release. Individual img file downloads are no longer supported.',
                'direct_url_not_supported': 'Direct file URLs are no longer supported. Only rom.zip firmware packages are supported.',
                'validating_firmware_files': 'Validating firmware files...',
                'copying_missing_files': 'Copying {count} missing files from assets...',
                'validating_file_integrity': 'Validating file integrity...',
                'firmware_package_validated': 'Firmware package validated successfully ({count} files)',
                'critical_files_missing': 'Critical files missing: {files}. Firmware package is incomplete.',
                'file_too_small': 'File {file} is too small ({size} bytes). Expected at least {min_size} bytes.',
                'failed_to_copy_file': 'Failed to copy {file}: {error}',
                'flash_in_progress_warning': 'Firmware flashing is still in progress. Are you sure you want to close this window?\n\nClosing now may interrupt the flash process and could damage your device.',
                
                # Screen frame titles
                'y1_remote_control': 'Y1 Remote Control',
                'please_unplug_turn_off_update_restore': 'Please unplug turn off your Y1 and Update / Restore',
                
                # Process termination
                'terminating_processes': 'Terminating ADB and Python processes...',
                'processes_terminated': 'Processes terminated successfully',
                'save_work_warning': 'Please save your work before continuing',
                
                # Error messages
                'connection_error': 'Connection error',
                'timeout_error': 'Operation timed out',
                'permission_error': 'Permission denied',
                'file_not_found': 'File not found',
                'invalid_input': 'Invalid input',
                
                # Status messages
                'ready': 'Ready',
                'busy': 'Busy',
                'idle': 'Idle',
                'processing': 'Processing...',
                'completed': 'Completed',
                'failed': 'Failed',
                'cancelled': 'Cancelled',
                
                # Device menu items
                'device_info': 'Device Info',
                'adb_shell': 'ADB Shell',
                'file_explorer': 'File Explorer',
                'take_screenshot': 'Take Screenshot',
                'recent_apps': 'Recent Apps',
                'change_device_language': 'Change Device Language',
                'sync_device_time': 'Sync Device Time',
                'install_firmware': 'Update',
                'how_to_update_restore': 'How to Update/Restore',
                'rockbox_utility': 'Rockbox Utility',
                'sp_flash_tool': 'SP Flash Tool',
                'restart_device': 'Restart Device',
                
                # Help menu items
                'reinstall_app': 'Reinstall App',
                'update_app': 'Update App',
                'run_older_version': 'Run Older Version',
                'become_patron': 'Become a Patron',
                
                # Debug menu items
                'toggle_debug_output': 'Toggle Debug Output',
                'change_update_branch': 'Change Update Branch...',
                'show_current_branch': 'Show Current Branch',
                'run_updater': 'Run Updater',
                
                # App actions
                'restart_rockbox': 'Restart Rockbox',
                'app_info': 'App Info',
                
                # Dialog messages
                'confirm_operation': 'Confirm Operation',
                'operation_confirmation': 'Are you sure you want to perform this operation?',
                'device_not_connected_warning': 'Device is not connected. Please connect a device first.',
                'no_device_found': 'No device found. Please ensure your device is connected and USB debugging is enabled.',
                'connection_failed': 'Connection failed. Please check your device connection.',
                'operation_in_progress': 'Operation in progress. Please wait...',
                'operation_completed': 'Operation completed successfully.',
                'operation_failed_with_error': 'Operation failed: {error}',
                
                # File operations
                'select_file': 'Select File',
                'select_folder': 'Select Folder',
                'file_selected': 'File selected: {filename}',
                'folder_selected': 'Folder selected: {foldername}',
                'no_file_selected': 'No file selected',
                'file_not_found_error': 'File not found: {filename}',
                'file_access_error': 'Cannot access file: {filename}',
                
                # Installation messages
                'installing_app': 'Installing app...',
                'app_installation_complete': 'App installation completed successfully',
                'app_installation_failed': 'App installation failed',
                'uninstalling_app': 'Uninstalling app...',
                'app_uninstallation_complete': 'App uninstallation completed successfully',
                'app_uninstallation_failed': 'App uninstallation failed',
                
                # Screenshot messages
                'taking_screenshot': 'Taking screenshot...',
                'screenshot_saved': 'Screenshot saved successfully',
                'screenshot_failed': 'Failed to take screenshot',
                
                # Time sync messages
                'syncing_device_time': 'Syncing device time...',
                'device_time_synced': 'Device time synchronized successfully',
                'device_time_sync_failed': 'Failed to sync device time',
                
                # Firmware messages
                'selecting_firmware': 'Selecting firmware...',
                'firmware_selected': 'Firmware selected: {filename}',
                'firmware_validation_failed': 'Firmware validation failed',
                'firmware_file_corrupted': 'Firmware file appears to be corrupted',
                
                # Update messages
                'checking_for_updates': 'Checking for updates...',
                'update_available_version': 'Update available: Version {version}',
                'no_updates_available': 'No updates available. You are running the latest version.',
                'update_download_failed': 'Failed to download update',
                'update_installation_failed': 'Failed to install update',
                'update_installation_complete': 'Update installed successfully. Please restart the application.',
                
                # Cache messages
                'cache_initialization_failed': 'Cache initialization failed',
                'cache_cleanup_failed': 'Cache cleanup failed',
                'cache_corrupted': 'Cache appears to be corrupted and will be rebuilt',
                
                # API messages
                'api_rate_limit_exceeded': 'API rate limit exceeded. Please wait before trying again.',
                'api_authentication_failed': 'API authentication failed',
                'api_connection_failed': 'API connection failed',
                'api_request_failed': 'API request failed',
                
                # Network messages
                'network_connection_failed': 'Network connection failed',
                'network_timeout': 'Network timeout',
                'network_unavailable': 'Network is currently unavailable',
                
                # System messages
                'system_error': 'System error occurred',
                'insufficient_permissions': 'Insufficient permissions to perform this operation',
                'resource_unavailable': 'Required resource is unavailable',
                'service_unavailable': 'Service is currently unavailable',
                
                # Validation messages
                'invalid_device_id': 'Invalid device ID',
                'invalid_file_format': 'Invalid file format',
                'invalid_parameter': 'Invalid parameter provided',
                'missing_required_field': 'Required field is missing',
                
                # Progress messages
                'initializing': 'Initializing...',
                'loading_configuration': 'Loading configuration...',
                'connecting_to_device': 'Connecting to device...',
                'disconnecting_from_device': 'Disconnecting from device...',
                'refreshing_data': 'Refreshing data...',
                'saving_settings': 'Saving settings...',
                'loading_settings': 'Loading settings...',
                
                # Warning messages
                'warning_device_disconnect': 'Warning: Device may disconnect during this operation',
                'warning_data_loss': 'Warning: This operation may result in data loss',
                'warning_unsaved_changes': 'Warning: You have unsaved changes',
                'warning_experimental_feature': 'Warning: This is an experimental feature',
                
                # Information messages
                'info_device_connected': 'Device connected successfully',
                'info_device_disconnected': 'Device disconnected',
                'info_operation_started': 'Operation started',
                'info_operation_completed': 'Operation completed',
                'info_settings_saved': 'Settings saved successfully',
                'info_settings_loaded': 'Settings loaded successfully',
                
                # Error details
                'error_details': 'Error Details',
                'error_code': 'Error Code',
                'error_message': 'Error Message',
                'error_stack_trace': 'Stack Trace',
                'error_time': 'Error Time',
                'error_location': 'Error Location',
                
                # Common actions
                'retry': 'Retry',
                'ignore': 'Ignore',
                'continue': 'Continue',
                'skip': 'Skip',
                'back': 'Back',
                'next': 'Next',
                'finish': 'Finish',
                'abort': 'Abort',
                'restart': 'Restart',
                'reset': 'Reset',
                'clear': 'Clear',
                'refresh': 'Refresh',
                'reload': 'Reload',
                'restore': 'Restore',
                'backup': 'Backup',
                'export': 'Export',
                'import': 'Import',
                'download': 'Download',
                'upload': 'Upload',
                'copy': 'Copy',
                'paste': 'Paste',
                'cut': 'Cut',
                'delete': 'Delete',
                'rename': 'Rename',
                'move': 'Move',
                'create': 'Create',
                'edit': 'Edit',
                'view': 'View',
                'search': 'Search',
                'find': 'Find',
                'replace': 'Replace',
                'select_all': 'Select All',
                'deselect_all': 'Deselect All',
                'invert_selection': 'Invert Selection',
                
                # Time and date
                'today': 'Today',
                'yesterday': 'Yesterday',
                'tomorrow': 'Tomorrow',
                'this_week': 'This Week',
                'last_week': 'Last Week',
                'next_week': 'Next Week',
                'this_month': 'This Month',
                'last_month': 'Last Month',
                'next_month': 'Next Month',
                'this_year': 'This Year',
                'last_year': 'Last Year',
                'next_year': 'Next Year',
                
                # File sizes
                'bytes': 'bytes',
                'kilobytes': 'KB',
                'megabytes': 'MB',
                'gigabytes': 'GB',
                'terabytes': 'TB',
                
                # Time units
                'seconds': 'seconds',
                'minutes': 'minutes',
                'hours': 'hours',
                'days': 'days',
                'weeks': 'weeks',
                'months': 'months',
                'years': 'years',
                
                # Status indicators
                'online': 'Online',
                'offline': 'Offline',
                'connected': 'Connected',
                'disconnected': 'Disconnected',
                'enabled': 'Enabled',
                'disabled': 'Disabled',
                'active': 'Active',
                'inactive': 'Inactive',
                'running': 'Running',
                'stopped': 'Stopped',
                'paused': 'Paused',
                'resumed': 'Resumed',
                'starting': 'Starting',
                'stopping': 'Stopping',
                'loading': 'Loading',
                'saving': 'Saving',
                'updating': 'Updating',
                'installing': 'Installing',
                'uninstalling': 'Uninstalling',
                'downloading': 'Downloading',
                'uploading': 'Uploading',
                'copying': 'Copying',
                'moving': 'Moving',
                'deleting': 'Deleting',
                'creating': 'Creating',
                'editing': 'Editing',
                'searching': 'Searching',
                'scanning': 'Scanning',
                'validating': 'Validating',
                'checking': 'Checking',
                'testing': 'Testing',
                'configuring': 'Configuring',
                'initializing': 'Initializing',
                'connecting': 'Connecting',
                'disconnecting': 'Disconnecting',
                'synchronizing': 'Synchronizing',
                'backing_up': 'Backing up',
                'restoring': 'Restoring',
                'exporting': 'Exporting',
                'importing': 'Importing',
                'compressing': 'Compressing',
                'decompressing': 'Decompressing',
                'encrypting': 'Encrypting',
                'decrypting': 'Decrypting',
                'verifying': 'Verifying',
                'repairing': 'Repairing',
                'optimizing': 'Optimizing',
                'cleaning': 'Cleaning',
                'rebuilding': 'Rebuilding',
                'refreshing': 'Refreshing',
                'reloading': 'Reloading',
                'restarting': 'Restarting',
                'resetting': 'Resetting',
                'clearing': 'Clearing',
                'restoring': 'Restoring',
                'backing_up': 'Backing up',
                'exporting': 'Exporting',
                'importing': 'Importing',
                'downloading': 'Downloading',
                'uploading': 'Uploading',
                'copying': 'Copying',
                'pasting': 'Pasting',
                'cutting': 'Cutting',
                'deleting': 'Deleting',
                'renaming': 'Renaming',
                'moving': 'Moving',
                'creating': 'Creating',
                'editing': 'Editing',
                'viewing': 'Viewing',
                'searching': 'Searching',
                'finding': 'Finding',
                'replacing': 'Replacing',
                'selecting_all': 'Selecting all',
                'deselecting_all': 'Deselecting all',
                'inverting_selection': 'Inverting selection',
                
                # Main UI elements
                'controls': 'Controls',
                'touch_screen_mode': 'Touch Screen Mode',
                'set_time': 'Set Time',
                'install_firmware': 'Update',
                'screenshot': 'Screenshot',
                'home': 'Home',
                'back': 'Back',
                'recent': 'Recent',
                'menu': 'Menu',
                'dpad_controls': 'D-pad Controls',
                'up': 'Up',
                'left': 'Left',
                'ok': 'OK',
                'right': 'Right',
                'down': 'Down',
                
                # Device screen messages
                'usb_connected': 'USB connected',
                'usb_connection_message': 'You\'ve connected to your computer via USB. Touch the button below if you want to copy files between your computer and your Android\'s SD card.',
                'turn_on_usb_storage': 'Turn on USB storage',
                'touch_screen_mode_for_system_app': 'Touch Screen Mode for system app',
                
                # Control instructions
                'touch_left_click': 'Touch: Left Click',
                'back_right_click': 'Back: Right Click',
                'dpad_instructions': 'D-pad: W/A/S/D or Arrow Keys sends DPAD_UP/DPAD_LEFT/DPAD_DOWN/DPAD_RIGHT',
                'enter_instructions': 'Enter: Wheel Click, Enter, E sends DPAD_CENTER',
                'toggle_alt': 'Toggle: Alt',
                
                # Scroll wheel mode
                'scroll_wheel_mode': 'Scroll Wheel Mode',
                'inverted': 'Inverted',
                'scroll_instructions': 'Scroll: W/S or Up/Down Arrows sends DPAD_UP/DPAD_DOWN',
                'scroll_instructions_inverted': 'Scroll: W/S or Up/Down Arrows sends DPAD_RIGHT/DPAD_LEFT',
                'dpad_instructions_inverted': 'D-pad: A/D or Left/Right Arrows sends DPAD_UP/DPAD_DOWN',
                
                # Status messages
                'scroll_wheel_mode_enabled': 'Scroll Wheel Mode enabled',
                'touch_screen_mode_enabled': 'Touch Screen Mode enabled',
                
                # Main UI elements
                'controls': 'Controls',
                'touch_screen_mode': 'Touch Screen Mode',
                'set_time': 'Set Time',
                'install_firmware': 'Update',
                'how_to_update_restore': 'How to Update/Restore',
                'screenshot': 'Screenshot',
                'home': 'Home',
                'back': 'Back',
                'recent': 'Recent',
                'menu': 'Menu',
                'dpad_controls': 'D-pad Controls',
                'up': 'Up',
                'left': 'Left',
                'ok': 'OK',
                'right': 'Right',
                'down': 'Down',
                
                # Device screen messages
                'usb_connected': 'USB connected',
                'usb_connection_message': 'You\'ve connected to your computer via USB. Touch the button below if you want to copy files between your computer and your Android\'s SD card.',
                'turn_on_usb_storage': 'Turn on USB storage',
                'touch_screen_mode_for_system_app': 'Touch Screen Mode for system app',
                
                # Control instructions
                'touch_left_click': 'Touch: Left Click',
                'back_right_click': 'Back: Right Click',
                'dpad_instructions': 'D-pad: W/A/S/D or Arrow Keys sends DPAD_UP/DPAD_LEFT/DPAD_DOWN/DPAD_RIGHT',
                'enter_instructions': 'Enter: Wheel Click, Enter, E sends DPAD_CENTER',
                'toggle_alt': 'Toggle: Alt',
                
                # Device status
                'device_screen': 'Device Screen',
                'connected_device': 'Connected Device',
                'disconnected_device': 'Disconnected Device',
                'connecting_device': 'Connecting to device...',
                'device_ready': 'Device Ready',
                'device_busy': 'Device Busy',
                'device_error': 'Device Error',
                
                # Button tooltips and labels
                'touch_screen_mode_tooltip': 'Switch to touch screen mode for direct device interaction',
                'set_time_tooltip': 'Synchronize device time with computer time',
                'install_firmware_tooltip': 'Update firmware to the connected device',
                'screenshot_tooltip': 'Take a screenshot of the device screen',
                'home_tooltip': 'Press home button on device',
                'back_tooltip': 'Press back button on device',
                'recent_tooltip': 'Show recent apps on device',
                'menu_tooltip': 'Press menu button on device',
                'up_tooltip': 'Press D-pad up',
                'left_tooltip': 'Press D-pad left',
                'ok_tooltip': 'Press D-pad center/OK',
                'right_tooltip': 'Press D-pad right',
                'down_tooltip': 'Press D-pad down',
                
                # Dialog titles and messages
                'confirm_action': 'Confirm Action',
                'information': 'Information',
                'warning': 'Warning',
                'error': 'Error',
                'success': 'Success',
                'notice': 'Notice',
                'attention': 'Attention',
                
                # File operations
                'file_operations': 'File Operations',
                'copy_files': 'Copy Files',
                'move_files': 'Move Files',
                'delete_files': 'Delete Files',
                'create_folder': 'Create Folder',
                'rename_file': 'Rename File',
                'file_properties': 'File Properties',
                'file_size': 'File Size',
                'file_date': 'File Date',
                'file_permissions': 'File Permissions',
                
                # Settings and preferences
                'settings': 'Settings',
                'preferences': 'Preferences',
                'configuration': 'Configuration',
                'options': 'Options',
                'advanced': 'Advanced',
                'basic': 'Basic',
                'custom': 'Custom',
                'default': 'Default',
                'reset_to_default': 'Reset to Default',
                'apply_settings': 'Apply Settings',
                'save_settings': 'Save Settings',
                'cancel_changes': 'Cancel Changes',
                'discard_changes': 'Discard Changes',
                
                # Connection status
                'connection_status': 'Connection Status',
                'connected': 'Connected',
                'disconnected': 'Disconnected',
                'connecting': 'Connecting...',
                'disconnecting': 'Disconnecting...',
                'connection_failed': 'Connection Failed',
                'connection_lost': 'Connection Lost',
                'reconnecting': 'Reconnecting...',
                
                # Progress and status
                'progress': 'Progress',
                'status': 'Status',
                'loading': 'Loading...',
                'saving': 'Saving...',
                'processing': 'Processing...',
                'initializing': 'Initializing...',
                'starting': 'Starting...',
                'stopping': 'Stopping...',
                'paused': 'Paused',
                'resumed': 'Resumed',
                'completed': 'Completed',
                'failed': 'Failed',
                'cancelled': 'Cancelled',
                'aborted': 'Aborted',
                'timeout': 'Timeout',
                'retrying': 'Retrying...',
                
                # Time and date
                'time': 'Time',
                'date': 'Date',
                'current_time': 'Current Time',
                'current_date': 'Current Date',
                'synchronize_time': 'Synchronize Time',
                'time_synchronized': 'Time Synchronized',
                'time_sync_failed': 'Time Synchronization Failed',
                
                # Device information
                'device_information': 'Device Information',
                'device_model': 'Device Model',
                'device_serial': 'Device Serial',
                'android_version': 'Android Version',
                'build_number': 'Build Number',
                'kernel_version': 'Kernel Version',
                'total_storage': 'Total Storage',
                'available_storage': 'Available Storage',
                'battery_level': 'Battery Level',
                'charging': 'Charging',
                'not_charging': 'Not Charging',
                'battery_full': 'Battery Full',
                'battery_low': 'Battery Low',
                
                # Firmware operations
                'firmware_operations': 'Firmware Operations',
                'select_firmware_file': 'Select Firmware File',
                'firmware_file': 'Firmware File',
                'firmware_version': 'Firmware Version',
                'firmware_size': 'Firmware Size',
                'firmware_checksum': 'Firmware Checksum',
                'validate_firmware': 'Validate Firmware',
                'firmware_valid': 'Firmware Valid',
                'firmware_invalid': 'Firmware Invalid',
                'flash_firmware': 'Flash Firmware',
                'firmware_flash_progress': 'Firmware Flash Progress',
                'firmware_flash_complete': 'Firmware Flash Complete',
                'firmware_flash_failed': 'Firmware Flash Failed',
                'backup_before_flash': 'Backup Before Flash',
                'backup_created': 'Backup Created',
                'backup_failed': 'Backup Failed',
                
                # App management
                'app_management': 'App Management',
                'installed_apps': 'Installed Apps',
                'system_apps': 'System Apps',
                'user_apps': 'User Apps',
                'app_name': 'App Name',
                'app_version': 'App Version',
                'app_size': 'App Size',
                'app_package': 'App Package',
                'app_install_date': 'Install Date',
                'app_last_updated': 'Last Updated',
                'app_permissions': 'App Permissions',
                'app_data': 'App Data',
                'app_cache': 'App Cache',
                'clear_app_data': 'Clear App Data',
                'clear_app_cache': 'Clear App Cache',
                'force_stop_app': 'Force Stop App',
                'uninstall_app': 'Uninstall App',
                'disable_app': 'Disable App',
                'enable_app': 'Enable App',
                
                # Screenshot and media
                'screenshot_taken': 'Screenshot Taken',
                'screenshot_saved': 'Screenshot Saved',
                'screenshot_failed': 'Screenshot Failed',
                'screenshot_location': 'Screenshot Location',
                'media_files': 'Media Files',
                'photos': 'Photos',
                'videos': 'Videos',
                'music': 'Music',
                'documents': 'Documents',
                'downloads': 'Downloads',
                
                # Network and connectivity
                'network_settings': 'Network Settings',
                'wifi_settings': 'WiFi Settings',
                'bluetooth_settings': 'Bluetooth Settings',
                'usb_settings': 'USB Settings',
                'adb_settings': 'ADB Settings',
                'usb_debugging': 'USB Debugging',
                'usb_debugging_enabled': 'USB Debugging Enabled',
                'usb_debugging_disabled': 'USB Debugging Disabled',
                'enable_usb_debugging': 'Enable USB Debugging',
                'disable_usb_debugging': 'Disable USB Debugging',
                
                # System operations
                'system_operations': 'System Operations',
                'reboot_device': 'Reboot Device',
                'shutdown_device': 'Shutdown Device',
                'restart_device': 'Restart Device',
                'factory_reset': 'Factory Reset',
                'wipe_data': 'Wipe Data',
                'wipe_cache': 'Wipe Cache',
                'wipe_dalvik': 'Wipe Dalvik Cache',
                'mount_system': 'Mount System',
                'unmount_system': 'Unmount System',
                'remount_system': 'Remount System',
                
                # Logs and debugging
                'logs': 'Logs',
                'debug_logs': 'Debug Logs',
                'system_logs': 'System Logs',
                'app_logs': 'App Logs',
                'adb_logs': 'ADB Logs',
                'log_level': 'Log Level',
                'log_verbose': 'Verbose',
                'log_debug': 'Debug',
                'log_info': 'Info',
                'log_warning': 'Warning',
                'log_error': 'Error',
                'clear_logs': 'Clear Logs',
                'export_logs': 'Export Logs',
                'save_logs': 'Save Logs',
                
                # Help and support
                'help_and_support': 'Help and Support',
                'user_manual': 'User Manual',
                'quick_start': 'Quick Start',
                'troubleshooting': 'Troubleshooting',
                'faq': 'FAQ',
                'contact_support': 'Contact Support',
                'report_bug': 'Report Bug',
                'feature_request': 'Feature Request',
                'about': 'About',
                'version_info': 'Version Information',
                'build_info': 'Build Information',
                'license': 'License',
                'credits': 'Credits',
                'changelog': 'Changelog',
                
                # Common phrases
                'yes': 'Yes',
                'no': 'No',
                'ok': 'OK',
                'cancel': 'Cancel',
                'close': 'Close',
                'exit': 'Exit',
                'quit': 'Quit',
                'restart': 'Restart',
                'refresh': 'Refresh',
                'reload': 'Reload',
                'reset': 'Reset',
                'clear': 'Clear',
                'delete': 'Delete',
                'remove': 'Remove',
                'add': 'Add',
                'create': 'Create',
                'edit': 'Edit',
                'modify': 'Modify',
                'change': 'Change',
                'update': 'Update',
                'upgrade': 'Upgrade',
                'downgrade': 'Downgrade',
                'install': 'Install',
                'uninstall': 'Uninstall',
                'enable': 'Enable',
                'disable': 'Disable',
                'start': 'Start',
                'stop': 'Stop',
                'pause': 'Pause',
                'resume': 'Resume',
                'continue': 'Continue',
                'skip': 'Skip',
                'retry': 'Retry',
                'ignore': 'Ignore',
                'abort': 'Abort',
                'finish': 'Finish',
                'complete': 'Complete',
                'done': 'Done',
                'ready': 'Ready',
                'busy': 'Busy',
                'idle': 'Idle',
                'active': 'Active',
                'inactive': 'Inactive',
                'online': 'Online',
                'offline': 'Offline',
                'available': 'Available',
                'unavailable': 'Unavailable',
                'enabled': 'Enabled',
                'disabled': 'Disabled',
                'visible': 'Visible',
                'hidden': 'Hidden',
                'show': 'Show',
                'hide': 'Hide',
                'expand': 'Expand',
                'collapse': 'Collapse',
                'minimize': 'Minimize',
                'maximize': 'Maximize',
                'restore': 'Restore',
                'backup': 'Backup',
                'restore_backup': 'Restore Backup',
                'create_backup': 'Create Backup',
                'export': 'Export',
                'import': 'Import',
                'download': 'Download',
                'upload': 'Upload',
                'sync': 'Sync',
                'synchronize': 'Synchronize',
                'search': 'Search',
                'find': 'Find',
                'replace': 'Replace',
                'select': 'Select',
                'deselect': 'Deselect',
                'select_all': 'Select All',
                'deselect_all': 'Deselect All',
                'invert_selection': 'Invert Selection',
                'copy': 'Copy',
                'paste': 'Paste',
                'cut': 'Cut',
                'duplicate': 'Duplicate',
                'rename': 'Rename',
                'move': 'Move',
                'sort': 'Sort',
                'filter': 'Filter',
                'group': 'Group',
                'ungroup': 'Ungroup',
                'lock': 'Lock',
                'unlock': 'Unlock',
                'protect': 'Protect',
                'unprotect': 'Unprotect',
                'encrypt': 'Encrypt',
                'decrypt': 'Decrypt',
                'compress': 'Compress',
                'decompress': 'Decompress',
                'archive': 'Archive',
                'extract': 'Extract',
                'validate': 'Validate',
                'verify': 'Verify',
                'check': 'Check',
                'test': 'Test',
                'scan': 'Scan',
                'analyze': 'Analyze',
                'optimize': 'Optimize',
                'repair': 'Repair',
                'clean': 'Clean',
                'defragment': 'Defragment',
                'format': 'Format',
                'partition': 'Partition',
                'mount': 'Mount',
                'unmount': 'Unmount',
                'eject': 'Eject',
                'safely_remove': 'Safely Remove',
                'connect': 'Connect',
                'disconnect': 'Disconnect',
                'pair': 'Pair',
                'unpair': 'Unpair',
                'configure': 'Configure',
                'setup': 'Setup',
                'wizard': 'Wizard',
                'assistant': 'Assistant',
                'guide': 'Guide',
                'tutorial': 'Tutorial',
                'demo': 'Demo',
                'preview': 'Preview',
                'view': 'View',
                'open': 'Open',
                'save': 'Save',
                'save_as': 'Save As',
                'new': 'New',
                'new_file': 'New File',
                'new_folder': 'New Folder',
                'new_project': 'New Project',
                'open_file': 'Open File',
                'open_folder': 'Open Folder',
                'open_project': 'Open Project',
                'recent_files': 'Recent Files',
                'recent_projects': 'Recent Projects',
                'favorites': 'Favorites',
                'bookmarks': 'Bookmarks',
                'history': 'History',
                'trash': 'Trash',
                'recycle_bin': 'Recycle Bin',
                'empty_trash': 'Empty Trash',
                'restore_from_trash': 'Restore from Trash',
                'properties': 'Properties',
                'details': 'Details',
                'information': 'Information',
                'statistics': 'Statistics',
                'summary': 'Summary',
                'overview': 'Overview',
                'contents': 'Contents',
                'index': 'Index',
                'table_of_contents': 'Table of Contents',
                'glossary': 'Glossary',
                'references': 'References',
                'bibliography': 'Bibliography',
                'appendix': 'Appendix',
                'notes': 'Notes',
                'comments': 'Comments',
                'annotations': 'Annotations',
                'highlights': 'Highlights',
                'bookmarks': 'Bookmarks',
                'tags': 'Tags',
                'labels': 'Labels',
                'categories': 'Categories',
                'folders': 'Folders',
                'directories': 'Directories',
                'paths': 'Paths',
                'locations': 'Locations',
                'destinations': 'Destinations',
                'sources': 'Sources',
                'targets': 'Targets',
                'origins': 'Origins',
                'destinations': 'Destinations',
                'inputs': 'Inputs',
                'outputs': 'Outputs',
                'results': 'Results',
                'outcomes': 'Outcomes',
                'consequences': 'Consequences',
                'effects': 'Effects',
                'impacts': 'Impacts',
                'influences': 'Influences',
                'factors': 'Factors',
                'elements': 'Elements',
                'components': 'Components',
                'parts': 'Parts',
                'pieces': 'Pieces',
                'sections': 'Sections',
                'segments': 'Segments',
                'divisions': 'Divisions',
                'subdivisions': 'Subdivisions',
                'branches': 'Branches',
                'subsections': 'Subsections',
                'chapters': 'Chapters',
                'sections': 'Sections',
                'paragraphs': 'Paragraphs',
                'sentences': 'Sentences',
                'words': 'Words',
                'characters': 'Characters',
                'bytes': 'Bytes',
                'bits': 'Bits',
                'kilobytes': 'KB',
                'megabytes': 'MB',
                'gigabytes': 'GB',
                'terabytes': 'TB',
                'petabytes': 'PB',
                'exabytes': 'EB',
                'zettabytes': 'ZB',
                'yottabytes': 'YB',
                'seconds': 'seconds',
                'minutes': 'minutes',
                'hours': 'hours',
                'days': 'days',
                'weeks': 'weeks',
                'months': 'months',
                'years': 'years',
                'decades': 'decades',
                'centuries': 'centuries',
                'millennia': 'millennia',
                'today': 'Today',
                'yesterday': 'Yesterday',
                'tomorrow': 'Tomorrow',
                'this_week': 'This Week',
                'last_week': 'Last Week',
                'next_week': 'Next Week',
                'this_month': 'This Month',
                'last_month': 'Last Month',
                'next_month': 'Next Month',
                'this_year': 'This Year',
                'last_year': 'Last Year',
                'next_year': 'Next Year',
                'morning': 'Morning',
                'afternoon': 'Afternoon',
                'evening': 'Evening',
                'night': 'Night',
                'midnight': 'Midnight',
                'noon': 'Noon',
                'dawn': 'Dawn',
                'dusk': 'Dusk',
                'sunrise': 'Sunrise',
                'sunset': 'Sunset',
                'spring': 'Spring',
                'summer': 'Summer',
                'autumn': 'Autumn',
                'winter': 'Winter',
                'fall': 'Fall',
                'january': 'January',
                'february': 'February',
                'march': 'March',
                'april': 'April',
                'may': 'May',
                'june': 'June',
                'july': 'July',
                'august': 'August',
                'september': 'September',
                'october': 'October',
                'november': 'November',
                'december': 'December',
                'monday': 'Monday',
                'tuesday': 'Tuesday',
                'wednesday': 'Wednesday',
                'thursday': 'Thursday',
                'friday': 'Friday',
                'saturday': 'Saturday',
                'sunday': 'Sunday',
                'mon': 'Mon',
                'tue': 'Tue',
                'wed': 'Wed',
                'thu': 'Thu',
                'fri': 'Fri',
                'sat': 'Sat',
                'sun': 'Sun',
                'jan': 'Jan',
                'feb': 'Feb',
                'mar': 'Mar',
                'apr': 'Apr',
                'may': 'May',
                'jun': 'Jun',
                'jul': 'Jul',
                'aug': 'Aug',
                'sep': 'Sep',
                'oct': 'Oct',
                'nov': 'Nov',
                'dec': 'Dec',
                
                # App installation and management
                'select_app_to_install': 'Select an app to install:',
                'install': 'Install',
                'cancel': 'Cancel',
                'mouse_input_panel': 'Mouse Input Panel (480x360)',
                'restart_rockbox': 'Restart Rockbox',
                'update_available': 'Update Available',
                'invert_scroll_direction': 'Invert Scroll Direction',
                'y1_helper_update_available': 'Y1 Helper Update Available',
                
                # Status messages
                'device_connected': 'Device connected',
                'device_disconnected_not_responsive': 'Device disconnected - not responsive',
                'first_time_install_firmware': 'First time? Install a Firmware from the Device Menu.',
                'app_detection_failed_touch_mode': 'App detection failed - Touch Screen Mode active',
                'screen_capture_started': 'Screen capture started',
                'toolbox_not_found': 'Toolbox not found on device',
                'device_time_synced': 'Device time synced successfully',
                'time_sync_failed': 'Time sync failed',
                'settings_launched': 'Settings launched',
                'failed_to_launch_settings': 'Failed to launch settings: {error}',
                'restarting_rockbox': 'Restarting Rockbox...',
                'rockbox_restarted': 'Rockbox restarted',
                'failed_to_restart_rockbox': 'Failed to restart Rockbox: {error}',
                'going_home': 'Going home...',
                'home_signal_sent': 'Home signal sent',
                'failed_to_send_home_signal': 'Failed to send home signal: {error}',
                'home_button_error': 'Home button error: {error}',
                'installing_apk': 'Installing APK...',
                'apk_installed_successfully': 'APK installed successfully',
                'apk_installation_failed_device_disconnected': 'APK installation failed: Device not connected',
                'apk_installation_failed_permission_denied': 'APK installation failed: Permission denied - check USB debugging',
                'apk_installation_failed_incompatible': 'APK installation failed: Incompatible APK or insufficient storage',
                'apk_installation_failed': 'APK installation failed: {error}',
                'apk_installation_cancelled': 'APK installation cancelled',
                'fetching_app_manifest': 'Fetching app manifest...',
                'downloading_app': 'Downloading {app_name}...',
                'installing_app': 'Installing app...',
                'app_installation_complete': 'App installation complete',
                'app_installation_failed': 'App installation failed',
                'app_installation_error': 'App installation error',
                'nova_launcher_opened': 'Nova Launcher opened',
                'keycode_display_app_opened': 'KeyCode Display app opened',
                'launcher_opened': 'Launcher {pkg} opened',
                'launched_app': 'Launched {app_name}',
                'failed_to_launch_app': 'Failed to launch {app_name}: {error}',
                'uninstalling_app': 'Uninstalling {app_name}...',
                'app_uninstalled_successfully': '{app_name} uninstalled successfully',
                'failed_to_uninstall_app': 'Failed to uninstall {app_name}: {error}',
                'launcher_control_status': 'Launcher control {status}',
                'tap_coordinates': 'Tap: ({x}, {y})',
                'touch_tap_failed': 'Touch tap failed',
                'swipe_coordinates': 'Swipe: ({start_x},{start_y}) → ({end_x},{end_y})',
                'touch_swipe_failed': 'Touch swipe failed',
                'enter_key_sent': 'Enter key sent',
                'enter_key_failed': 'Enter key failed: {error}',
                'touch_input_sent': 'Touch input sent to ({x}, {y})',
                'touch_input_failed': 'Touch input failed: {error}',
                'back_button_pressed': 'Back button pressed',
                'back_button_failed': 'Back button failed: {error}',
                'dpad_pressed': 'D-pad {direction} pressed',
                'dpad_failed': 'D-pad {direction} failed: {error}',
                'mouse_wheel_click': 'Mouse wheel click: {action} pressed',
                'mouse_wheel_click_failed': 'Mouse wheel click failed: {error}',
                'key_pressed': 'Key {direction} pressed',
                'key_failed': 'Key {direction} failed: {error}',
                'ready': 'Ready',
                'opening_language_settings': 'Opening language settings...',
                'language_settings_opened': 'Language settings opened',
                'failed_to_open_language_settings': 'Failed to open language settings: {error}',
                'device_restarting': 'Device restarting...',
                'failed_to_restart_device': 'Failed to restart device: {error}',
                'rockbox_utility_launched': 'Rockbox Utility launched',
                'rockbox_utility_launched_admin': 'Rockbox Utility launched (Admin)',
                'rockbox_utility_launched_runas': 'Rockbox Utility launched (RunAs)',
                'launching_rockbox_utility': 'Launching Rockbox Utility...',
                'sp_flash_tool_launched': 'SP Flash Tool launched',
                'failed_to_stop_rockbox': 'Failed to stop Rockbox: {error}',
                'scroll_wheel_mode_y1_launcher': 'Scroll Wheel Mode with Invert for Y1 Launcher',
                'scroll_wheel_mode_rockbox': 'Scroll Wheel Mode for Rockbox',
                'scroll_wheel_mode_y1_app': 'Scroll Wheel Mode with Invert for Y1 App',
                'touch_screen_mode_system_app': 'Touch Screen Mode for system app',
                'touch_screen_mode_other_app': 'Touch Screen Mode for other app',
                'screenshot_saved': 'Screenshot saved: {filename}',
                'screenshot_failed': 'Screenshot failed',
                'back_button_virtual_nav': 'Back button (virtual nav bar) pressed',
                'home_button_virtual_nav': 'Home button (virtual nav bar) pressed',
                'recent_apps_opened': 'Recent Apps opened',
                'updater_launched': 'Updater launched',
                'path_items': 'Path: {path} | Items: {count}',
                'copied_items': 'Copied {count} item(s) to clipboard',
                'cut_items': 'Cut {count} item(s) to clipboard',
                
                # Firmware installation
                'uninstalling_rockbox': 'Uninstalling Rockbox...',
                'removing_rockbox_directories': 'Removing Rockbox directories...',
                'fetching_stock_rom_info': 'Fetching stock ROM information...',
                'installing_stock_rom': 'Installing stock ROM...',
                'ok': 'OK',
                'fetching_firmware_manifest': 'Fetching firmware manifest...',
                'turn_off_unplug_y1_continue': 'Please turn off and unplug your Y1, then click Continue to proceed.',
                'continue': 'Continue',
                'preparing_rom_files': 'Preparing ROM files...',
                'make_sure_y1_off_disconnected': 'Please make sure your Y1 is turned off and disconnected.',
                'initializing': 'Initializing...',
                'select_firmware_to_install': 'Select a firmware to install:',
                'browse_firmware_img': 'Browse Firmware (.img)',
                'close': 'Close',
                'update_available_exclamation': 'Update Available!',
                'would_you_like_to_update_now': 'Would you like to update now?',
                'update_now': 'Update Now',
                'later': 'Later',
                'choose_update_method': 'Choose your update method:',
                'quick_update_patch': 'Quick Update (Patch)',
                'full_update_installer': 'Full Update (Installer)',
                'update': 'Update',
                
                # File explorer
                'up': 'Up',
                'home': 'Home',
                'root': 'Root',
                'refresh': 'Refresh',
                'path': 'Path:',
                'copy': 'Copy',
                'cut': 'Cut',
                'paste': 'Paste',
                'delete': 'Delete',
                'rename': 'Rename',
                'new_folder': 'New Folder',
                'new_file': 'New File',
                'name': 'Name',
                'size': 'Size',
                'permissions': 'Permissions',
                'owner': 'Owner',
                'modified': 'Modified',
                'open': 'Open',
                'open_in_new_window': 'Open in New Window',
                'properties': 'Properties',
                
                # Menu items
                'help_update_available': 'Help - Update Available',
                'quick_update': 'Quick Update',
                'full_install': 'Full Install',
                'update_app': 'Update App',
                'repair_app': 'Repair App',
                'go_home': 'Go Home',
                'open_settings': 'Open Settings',
                'recent_apps': 'Recent Apps',
                'r_innioasis': 'r/innioasis',
                'innioasis_discord': 'Innioasis / Timmkoo Discord',
                'debug': 'Debug',
                
                # Firmware Progress Indicators
                'please_unplug_turn_off': 'Please unplug and turn off your Y1 now',
                'device_detected_flashing': 'Device detected, now flashing...',
                'searching_usb_device': 'Flash tool is searching for USB device. Please connect your turned-off Y1 device.',
                'downloading_firmware': 'Downloading firmware... {percent}%',
                'flashing_firmware_progress': 'Flashing firmware... {percent}%',
                'preparing': 'Preparing: {message}',
                'flashing': 'Flashing: {message}',
                'finalizing': 'Finalizing: {message}',
                'flash_completed_success': 'Flash completed successfully!',
                'flash_completed_verification': 'Flash completed - verification needed',
                'flash_error_occurred': 'Flash error occurred',
                'connection_failed': 'Connection failed',
                'flash_tool_output': 'Flash Tool Output',
                
                # New firmware validation and error messages
                'rom_zip_not_found': 'rom.zip not found in firmware release. Individual img file downloads are no longer supported.',
                'direct_url_not_supported': 'Direct file URLs are no longer supported. Only rom.zip firmware packages are supported.',
                'validating_firmware_files': 'Validating firmware files...',
                'copying_missing_files': 'Copying {count} missing files from assets...',
                'validating_file_integrity': 'Validating file integrity...',
                'firmware_package_validated': 'Firmware package validated successfully ({count} files)',
                'critical_files_missing': 'Critical files missing: {files}. Firmware package is incomplete.',
                'file_too_small': 'File {file} is too small ({size} bytes). Expected at least {min_size} bytes.',
                'failed_to_copy_file': 'Failed to copy {file}: {error}',
                'flash_in_progress_warning': 'Firmware flashing is still in progress. Are you sure you want to close this window?\n\nClosing now may interrupt the flash process and could damage your device.',
                
                # Screen frame titles
                'y1_remote_control': 'Y1 Remote Control',
                'please_unplug_turn_off_update_restore': 'Please unplug turn off your Y1 and Update / Restore',
                
                # Common dialog buttons
                'innioasis_subreddit': 'Innioasis Subreddit',
                'get_priority_support': 'Get Priority Support',
                'modders_discord': 'Modders\' Discord'
            }
        }
    

    
    def get_text(self, key: str, **kwargs) -> str:
        """Get English text for the given key"""
        try:
            if key in self.translations['en_US']:
                text = self.translations['en_US'][key]
                # Format the text with any provided parameters
                if kwargs:
                    text = text.format(**kwargs)
                return text
            
            # Return the key itself if no translation found
            return key
            
        except Exception:
            return key
    

    
    def get_current_language(self) -> str:
        """Get current language code"""
        return self.current_language

# Global instance
localization_manager = LocalizationManager()

def get_text(key: str, **kwargs) -> str:
    """Global function to get translated text"""
    return localization_manager.get_text(key, **kwargs)


